services:

  postgres:
    image: postgres:13
    container_name: pg_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.2-python3.10
    container_name: airflow_container
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://root:root@postgres:5432/main
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      airflow webserver & airflow scheduler"

  python_etl:
    build: .
    container_name: python_etl_container
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin  
    ports:
      - "5050:80"  
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  

volumes:
  pgdata:
  pgadmin_data:
